name: Deployment Workflow

on:
  workflow_run:
    workflows: [ "CI/CD Workflow" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: pull image from docker
        run: sudo docker pull ogleh/ci-cd-repository:latest

      - name: delete docker container
        run: sudo docker rm -f ci-cd-container || true

      - name: running the new docker container
        run: sudo docker run -d --name ci-cd-container -p80:8080 ogleh/ci-cd-repository:latest


#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn clean package
#
#      - name: Log in to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and Push Docker Image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: ogleh/ci-cd-repository:v1,ogleh/ci-cd-repository:latest
#
#      - name: Execute deployment script on EC2
#        uses: appleboy/ssh-action@v0.1.1
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ec2-user
#          port: 22
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          # passphrase: ${{ secrets.EC2_PASSPHRASE }} # Optional, if your key has a passphrase
#          script: |
#            docker pull ogleh/ci-cd-repository:latest
#            docker stop ci-cd-container || true
#            docker rm ci-cd-container || true
#            docker run -d --name ci-cd-container -p80:8080 ogleh/ci-cd-repository:latest
